name: Build and deploy ASP.Net Core app to Azure Web App - app-20241018-demo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}\myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}\myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_99CB162A3FFB429D844084E3ED8C2AF6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E104DE6EE35645B0B831E84C8B41D204 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6CAB8DE766BD4D4CB3F43A876E73A71A }}

      - name: Log variables
        run: |
          echo "Resource Group: ${{ vars.RESOURCE_GROUP }}"
          echo "App Service Plan: ${{ vars.APP_SERVICE_PLAN }}"

      - name: Create Azure Web App (only for pull requests)
        if: github.event_name == 'pull_request'
        run: |
          az webapp create --resource-group ${{ vars.RESOURCE_GROUP }} --plan ${{ vars.APP_SERVICE_PLAN }} --name apptest-${{ github.sha }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ github.event_name == 'pull_request' && 'apptest-' + github.sha || 'app-20241018-demo' }}
          slot-name: 'Production'
          package: .
